// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuez5YuyTW2Hj1-XU4JNPcsrLFEAbd2R8',
    appId: '1:344033296126:web:055598f52237128fc96faf',
    messagingSenderId: '344033296126',
    projectId: 'supplier-barang',
    authDomain: 'supplier-barang.firebaseapp.com',
    storageBucket: 'supplier-barang.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfluMzkKUbeWHw-dzBdLELQCAVR31hm_I',
    appId: '1:344033296126:android:e0205b76db4e0f6cc96faf',
    messagingSenderId: '344033296126',
    projectId: 'supplier-barang',
    storageBucket: 'supplier-barang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqO3R5RiDVIdzoGw-8sSzvvK9MEvdSAM',
    appId: '1:344033296126:ios:6896439f46fbf523c96faf',
    messagingSenderId: '344033296126',
    projectId: 'supplier-barang',
    storageBucket: 'supplier-barang.firebasestorage.app',
    iosBundleId: 'com.example.suplierApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAqO3R5RiDVIdzoGw-8sSzvvK9MEvdSAM',
    appId: '1:344033296126:ios:6896439f46fbf523c96faf',
    messagingSenderId: '344033296126',
    projectId: 'supplier-barang',
    storageBucket: 'supplier-barang.firebasestorage.app',
    iosBundleId: 'com.example.suplierApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuez5YuyTW2Hj1-XU4JNPcsrLFEAbd2R8',
    appId: '1:344033296126:web:24e1594ef9e52dd0c96faf',
    messagingSenderId: '344033296126',
    projectId: 'supplier-barang',
    authDomain: 'supplier-barang.firebaseapp.com',
    storageBucket: 'supplier-barang.firebasestorage.app',
  );
}
